#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/bastion

devops_user: ravinder

packages:
  - vim
  - zip
  - unzip
  - git
  - curl
  - wget
  - htop
  - jq
  - net-tools
  - tree

ssh_port: 22

kubectl_version: "1.35"