---
- name: Create user
  user:
    name: "{{ devops_user }}"
    shell: /bin/bash
    create_home: yes
    groups: sudo, docker
    append: yes

- name: Create .ssh directory
  file:
    path: "/home/{{ devops_user }}/.ssh"
    state: directory
    owner: "{{ devops_user }}"
    group: "{{ devops_user }}"
    mode: '0700'

- name: Add authorized keys
  authorized_key:
    user: "{{ devops_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub' )}}"
