{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  labels:
    {{ include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.usernameKey }}: {{ .Values.auth.username | quote }}
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.password | quote }}
{{- end }}
