fullnameOverride: prometheus

defaultRules:
  create: true
  rules:
    etcd: false
    kubeScheduler: false

alertmanager:
  enabled: true
  service:
    type: ClusterIP
  alertmanagerSpec:
    replicas: 1
    retention: 120h
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: standard
          resources:
            requests:
              storage: 2Gi

grafana:
  enabled: true

  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: browser

  initChownData:
    securityContext:
      capabilities:
        add:
          - CHOWN
          - DAC_OVERRIDE
          - FOWNER
        drop:
          - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      runAsUser: 0
      seccompProfile:
        type: RuntimeDefault

  persistence:
    enabled: true
    storageClassName: standard
    size: 2Gi

  service:
    type: ClusterIP

  serviceMonitor:
    enabled: true
    interval: 30s

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      editable: true


prometheusOperator:
  admissionWebhooks:
    patch:
      enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    replicas: 1
    retention: 7d
    retentionSize: 8GB
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: standard
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
