fullnameOverride: tempo

replicas: 1

tempo:
  retention: 72h

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

service:
  type: ClusterIP

serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus

persistence:
  enabled: true
  storageClassName: standard
  size: 10Gi
