replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "17"

nameOverride: ""
fullnameOverride: ""

statefulset:
  nameOverride: ""

auth:
  database: lumiere
  username: admin
  password: postgres
  existingSecret: ""
  usernameKey: POSTGRES_USER
  passwordKey: POSTGRES_PASSWORD

service:
  nameOverride: ""
  type: ClusterIP
  clusterIP: None
  port: 5432

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 999

securityContext:
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClassName: ""

probes:
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 20

nodeSelector: {}
tolerations: []
affinity: {}
