apiVersion: batch/v1
kind: Job
metadata:
  name: lumiere-db-sync
  namespace: lumiere
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: prisma-db-push
          image: docker.io/ravinder50300/lumiere-backend:v1.0.3
          imagePullPolicy: Always
          command: ["npx", "prisma", "db", "push"]
          envFrom:
            - secretRef:
                name: lumiere-app-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
