apiVersion: v1
kind: Secret
metadata:
  name: lumiere-db-secret
  namespace: lumiere
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "postgres"

---

apiVersion: v1
kind: Secret
metadata:
  name: lumiere-app-secret
  namespace: lumiere
type: Opaque
stringData:
  DATABASE_URL: "postgresql://admin:postgres@postgres:5432/lumiere?schema=public"
  JWT_ACCESS_SECRET: "jwt-secure-secret"
  JWT_REFRESH_SECRET: "jwt-refresh-secret"
  JWT_ACCESS_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  PORT: "4000"
  NODE_ENV: "production"
  STRIPE_SECRET_KEY: "sk_test_replace_me"
  STRIPE_WEBHOOK_SECRET: "whsec_replace_me"
